# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_text', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('description_text', models.CharField(default='insert a description here', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dcc',
            fields=[
                ('dcc_text', models.CharField(choices=[(None, 'Select a dcc'), ('act360', 'Act360'), ('act365', 'Act365')], default=None, max_length=20, primary_key=True, serialize=False)),
                ('description_text', models.CharField(default='insert a description here', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('pub_dateTimeRef', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date time reference')),
                ('lowPrice', models.FloatField(default=None)),
                ('highPrice', models.FloatField(default=None)),
                ('openPrice', models.FloatField(default=None)),
                ('closePrice', models.FloatField(default=None)),
                ('description_text', models.CharField(default='insert a description here', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HistorySeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(default='insert a description here', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IborIndex',
            fields=[
                ('underlyingy_text', models.CharField(default=None, max_length=11, primary_key=True, serialize=False)),
                ('description_text', models.CharField(default='insert a description here', max_length=500)),
                ('periodNbUnits_integer', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hlwsfinapp.Currency')),
                ('dcc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hlwsfinapp.Dcc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodUnit',
            fields=[
                ('period_unit_text', models.CharField(choices=[(None, 'Select a period unit.'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default=None, max_length=20, primary_key=True, serialize=False)),
                ('description_text', models.CharField(default='insert a description here', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='iborindex',
            name='periodUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hlwsfinapp.PeriodUnit'),
        ),
        migrations.AddField(
            model_name='historyentry',
            name='historySeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlwsfinapp.HistorySeries'),
        ),
    ]
