# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwsfinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iborindex',
            name='underlyingy_text',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
