# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwsfinapp', '0002_auto_20151219_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyentry',
            name='historySeries',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_text',
        ),
        migrations.RemoveField(
            model_name='dcc',
            name='dcc_text',
        ),
        migrations.RemoveField(
            model_name='iborindex',
            name='underlyingy_text',
        ),
        migrations.RemoveField(
            model_name='periodunit',
            name='period_unit_text',
        ),
        migrations.AddField(
            model_name='currency',
            name='ref_name',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dcc',
            name='ref_name',
            field=models.CharField(choices=[(None, 'Select a dcc'), ('act360', 'Act360'), ('act365', 'Act365')], default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='iborindex',
            name='ref_name',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='periodunit',
            name='ref_name',
            field=models.CharField(choices=[(None, 'Select a period unit.'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='description_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dcc',
            name='description_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='iborindex',
            name='description_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='periodunit',
            name='description_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='HistoryEntry',
        ),
        migrations.DeleteModel(
            name='HistorySeries',
        ),
    ]
