# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlwsfinapp', '0003_auto_20151220_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dcc',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='iborindex',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='periodunit',
            name='description_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
